#!/usr/bin/env bash
set -Eeuo pipefail

BASE_DIR="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="$BASE_DIR/.env"
RUNTIME_FILE="$BASE_DIR/config/runtime.env"
APPS_RUNTIME_FILE="$BASE_DIR/apps/runtime.env"
ARGOCD_RUNTIME_FILE="$BASE_DIR/argocd/runtime.env"
IMAGES_FILE="$BASE_DIR/config/images.env"
APPS_IMAGES_FILE="$BASE_DIR/apps/images.env"
OPTIONAL_GROUPS=(identity db-admin)

if [[ ! -f "$ENV_FILE" ]]; then
  echo "❌ Missing .env file at $ENV_FILE"
  echo "   Run: cp .env.example .env"
  echo "   Then edit .env and run: make configure"
  exit 1
fi

set -a
# shellcheck disable=SC1090
source "$ENV_FILE"
set +a

APP_DOMAIN="${APP_DOMAIN:-127.0.0.1.nip.io}"
REPO_URL="${REPO_URL:-https://github.com/chinmaymjog/k3s-argocd-sandbox.git}"
TARGET_REVISION="${TARGET_REVISION:-main}"
ADMINER_IMAGE="${ADMINER_IMAGE:-adminer:5.4.2}"
GRAFANA_IMAGE="${GRAFANA_IMAGE:-grafana/grafana-oss:13.0.1}"
KEYCLOAK_IMAGE="${KEYCLOAK_IMAGE:-quay.io/keycloak/keycloak:24.0.0}"
MYSQL_IMAGE="${MYSQL_IMAGE:-mysql:8.0}"
N8N_IMAGE="${N8N_IMAGE:-docker.n8n.io/n8nio/n8n:2.18.7}"
PGSQL_IMAGE="${PGSQL_IMAGE:-postgres:15}"
PHPMYADMIN_IMAGE="${PHPMYADMIN_IMAGE:-phpmyadmin:5.2.3}"
PROMETHEUS_IMAGE="${PROMETHEUS_IMAGE:-prom/prometheus:v3.11.3}"

write_runtime_file() {
  local target="$1"
  cat > "$target" <<EOF
# Generated by scripts/configure-runtime.sh
# Source of truth: .env
# Do not edit this file by hand.
APP_DOMAIN=$APP_DOMAIN
REPO_URL=$REPO_URL
TARGET_REVISION=$TARGET_REVISION
ARGOCD_HOST=argocd.$APP_DOMAIN
ADMINER_HOST=adminer.$APP_DOMAIN
GRAFANA_HOST=grafana.$APP_DOMAIN
KEYCLOAK_HOST=keycloak.$APP_DOMAIN
N8N_HOST=n8n.$APP_DOMAIN
N8N_WEBHOOK_URL=https://n8n.$APP_DOMAIN/
PHPMYADMIN_HOST=phpmyadmin.$APP_DOMAIN
PROMETHEUS_HOST=prometheus.$APP_DOMAIN
EOF
}

write_runtime_file "$RUNTIME_FILE"
write_runtime_file "$APPS_RUNTIME_FILE"
write_runtime_file "$ARGOCD_RUNTIME_FILE"

cat > "$IMAGES_FILE" <<EOF
# Generated by scripts/configure-runtime.sh
# Source of truth: .env
# Do not edit this file by hand.
ADMINER_IMAGE=$ADMINER_IMAGE
GRAFANA_IMAGE=$GRAFANA_IMAGE
KEYCLOAK_IMAGE=$KEYCLOAK_IMAGE
MYSQL_IMAGE=$MYSQL_IMAGE
N8N_IMAGE=$N8N_IMAGE
PGSQL_IMAGE=$PGSQL_IMAGE
PHPMYADMIN_IMAGE=$PHPMYADMIN_IMAGE
PROMETHEUS_IMAGE=$PROMETHEUS_IMAGE
EOF

echo "✅ Wrote runtime mirrors to $RUNTIME_FILE, $APPS_RUNTIME_FILE, and $ARGOCD_RUNTIME_FILE"
cp "$IMAGES_FILE" "$APPS_IMAGES_FILE"
echo "✅ Wrote image mirrors to $IMAGES_FILE and $APPS_IMAGES_FILE"

for group in "${OPTIONAL_GROUPS[@]}"; do
  group_dir="$BASE_DIR/apps/optional/$group"
  if [[ -d "$group_dir" ]]; then
    write_runtime_file "$group_dir/runtime.env"
    cp "$IMAGES_FILE" "$group_dir/images.env"
    echo "✅ Wrote optional group mirrors to $group_dir"
  fi
done
