apiVersion: v1
kind: Secret
metadata:
  name: sandbox-secrets
  namespace: default
type: Opaque
data:
  # Base64 encoded 'password' for all databases to keep local setup easy
  POSTGRES_PASSWORD: cGFzc3dvcmQ=
  MYSQL_ROOT_PASSWORD: cGFzc3dvcmQ=
  KEYCLOAK_DB_PASSWORD: cGFzc3dvcmQ=
  N8N_DB_PASSWORD: cGFzc3dvcmQ=
  GRAFANA_DB_PASSWORD: cGFzc3dvcmQ=
  KEYCLOAK_ADMIN_PASSWORD: cGFzc3dvcmQ=
  N8N_ENCRYPTION_KEY: c29tZS1zZWNyZXQta2V5
